--
--
--
CREATE TABLE IF NOT EXISTS account
(
    account_id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2000),
    created_date            TIMESTAMP WITH TIME ZONE NOT NULL        DEFAULT NOW(),
    first_name              VARCHAR(100)             NOT NULL,
    last_name               VARCHAR(100)             NOT NULL,
    email                   VARCHAR(100)             NOT NULL UNIQUE,
    user_handle             VARCHAR(128)             NOT NULL UNIQUE DEFAULT ENCODE(gen_random_bytes(64), 'hex'), -- an opaque id used for webauthn
    is_enabled              BOOLEAN                  NOT NULL        DEFAULT TRUE,
    is_account_locked       BOOLEAN                  NOT NULL        DEFAULT FALSE,
    is_account_expired      BOOLEAN                  NOT NULL        DEFAULT FALSE,
    has_credentials_expired BOOLEAN                  NOT NULL        DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS account_email_idx ON account (email);
CREATE INDEX IF NOT EXISTS account_user_handle_idx ON account (user_handle);
CREATE INDEX IF NOT EXISTS account_is_enabled_idx ON account (is_enabled);
CREATE INDEX IF NOT EXISTS account_is_account_locked_idx ON account (is_account_locked);
CREATE INDEX IF NOT EXISTS account_is_account_expired_idx ON account (is_account_expired);
CREATE INDEX IF NOT EXISTS account_has_credentials_expired_idx ON account (has_credentials_expired);

CREATE TABLE IF NOT EXISTS credentials
(
    credentials_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_date       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    credential_id      VARCHAR(512)             NOT NULL UNIQUE,
    user_handle        VARCHAR(128)             NOT NULL REFERENCES account (user_handle) ON DELETE CASCADE,
    public_key_cose    TEXT                     NOT NULL,
    signature_count    INT                               DEFAULT 0,
    is_user_verified   BOOLEAN                           DEFAULT FALSE,
    is_discoverable    BOOLEAN, -- can be unknown!
    is_backup_eligible BOOLEAN                           DEFAULT FALSE,
    is_backed_up       BOOLEAN                           DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS credentials_credential_id_idx ON credentials (credential_id);
CREATE INDEX IF NOT EXISTS credentials_user_handle_idx ON credentials (user_handle);
CREATE INDEX IF NOT EXISTS credentials_signature_count_idx ON credentials (signature_count);
CREATE INDEX IF NOT EXISTS credentials_is_user_verified_idx ON credentials (is_user_verified);
CREATE INDEX IF NOT EXISTS credentials_is_discoverable_idx ON credentials (is_discoverable);
CREATE INDEX IF NOT EXISTS credentials_is_backup_eligible_idx ON credentials (is_backup_eligible);
CREATE INDEX IF NOT EXISTS credentials_is_backed_up_idx ON credentials (is_backed_up);

--
-- END
-- -
